2023-12-03 21:12:54,682 INFO Start polling
2023-12-03 21:12:58,327 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-03 21:14:14,704 INFO Polling stopped
2023-12-03 21:14:14,966 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-03 21:14:53,096 INFO Start polling
2023-12-03 21:14:53,203 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-03 21:14:53,337 INFO Update id=683638687 is not handled. Duration 0 ms by bot id=6768503726
2023-12-03 21:14:53,337 INFO Update id=683638688 is not handled. Duration 0 ms by bot id=6768503726
2023-12-03 21:14:55,386 INFO Update id=683638689 is not handled. Duration 0 ms by bot id=6768503726
2023-12-03 21:15:29,756 INFO Polling stopped
2023-12-03 21:15:30,363 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-03 21:22:33,902 INFO Start polling
2023-12-03 21:22:33,995 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-03 21:29:35,767 INFO Polling stopped
2023-12-03 21:29:36,394 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-03 22:37:41,193 INFO Start polling
2023-12-03 22:37:41,339 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-03 22:37:46,427 INFO Update id=683638690 is handled. Duration 360 ms by bot id=6768503726
2023-12-03 22:38:42,825 INFO Polling stopped
2023-12-03 22:38:43,363 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-03 22:38:45,395 INFO Start polling
2023-12-03 22:38:45,475 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-03 22:38:46,654 INFO Update id=683638691 is handled. Duration 280 ms by bot id=6768503726
2023-12-03 22:38:50,663 INFO Update id=683638692 is handled. Duration 171 ms by bot id=6768503726
2023-12-03 22:38:51,557 INFO Update id=683638693 is handled. Duration 140 ms by bot id=6768503726
2023-12-03 22:40:02,003 INFO Polling stopped
2023-12-03 22:40:02,571 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-03 22:40:04,465 INFO Start polling
2023-12-03 22:40:04,559 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-03 22:40:10,285 INFO Update id=683638694 is handled. Duration 375 ms by bot id=6768503726
2023-12-03 23:37:38,971 INFO Polling stopped
2023-12-03 23:37:39,541 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-03 23:37:42,594 INFO Start polling
2023-12-03 23:37:42,686 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-03 23:38:25,323 INFO Update id=683638695 is handled. Duration 296 ms by bot id=6768503726
2023-12-03 23:39:04,245 INFO Update id=683638696 is handled. Duration 312 ms by bot id=6768503726
2023-12-03 23:41:55,325 INFO Update id=683638697 is handled. Duration 264 ms by bot id=6768503726
2023-12-03 23:49:45,018 INFO Update id=683638698 is handled. Duration 343 ms by bot id=6768503726
2023-12-03 23:59:59,903 INFO Polling stopped
2023-12-04 00:00:00,455 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 20:42:59,887 INFO Start polling
2023-12-10 20:42:59,967 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 20:43:05,503 INFO Update id=683638700 is handled. Duration 296 ms by bot id=6768503726
2023-12-10 20:46:30,448 INFO Polling stopped
2023-12-10 20:46:31,164 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 20:46:36,604 INFO Start polling
2023-12-10 20:46:36,696 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 20:46:39,655 INFO Update id=683638701 is not handled. Duration 265 ms by bot id=6768503726
2023-12-10 20:46:39,655 ERROR Cause exception while process update id=683638701 by bot id=6768503726
ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
Traceback (most recent call last):
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\programming\swzy_bot\users\commands.py", line 13, in func_start
    markup = ReplyKeyboardMarkup()
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
2023-12-10 20:47:03,234 INFO Polling stopped
2023-12-10 20:47:03,838 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 20:47:30,018 INFO Start polling
2023-12-10 20:47:30,114 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 20:47:35,368 INFO Update id=683638702 is not handled. Duration 0 ms by bot id=6768503726
2023-12-10 20:47:35,368 ERROR Cause exception while process update id=683638702 by bot id=6768503726
ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
Traceback (most recent call last):
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\programming\swzy_bot\users\commands.py", line 12, in func_start
    markup = ReplyKeyboardMarkup()
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
2023-12-10 20:47:42,685 INFO Update id=683638703 is not handled. Duration 16 ms by bot id=6768503726
2023-12-10 20:47:42,685 ERROR Cause exception while process update id=683638703 by bot id=6768503726
ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
Traceback (most recent call last):
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\programming\swzy_bot\users\commands.py", line 12, in func_start
    markup = ReplyKeyboardMarkup()
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
2023-12-10 20:47:44,092 INFO Update id=683638704 is not handled. Duration 0 ms by bot id=6768503726
2023-12-10 20:47:44,093 ERROR Cause exception while process update id=683638704 by bot id=6768503726
ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
Traceback (most recent call last):
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\programming\swzy_bot\users\commands.py", line 12, in func_start
    markup = ReplyKeyboardMarkup()
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
2023-12-10 20:48:08,425 INFO Polling stopped
2023-12-10 20:48:09,052 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 20:48:15,336 INFO Start polling
2023-12-10 20:48:15,410 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 20:48:17,885 INFO Update id=683638705 is not handled. Duration 0 ms by bot id=6768503726
2023-12-10 20:48:17,885 ERROR Cause exception while process update id=683638705 by bot id=6768503726
ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
Traceback (most recent call last):
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\programming\swzy_bot\users\commands.py", line 12, in func_start
    markup = ReplyKeyboardMarkup()
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
2023-12-10 20:48:19,669 INFO Update id=683638706 is not handled. Duration 0 ms by bot id=6768503726
2023-12-10 20:48:19,670 ERROR Cause exception while process update id=683638706 by bot id=6768503726
ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
Traceback (most recent call last):
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\programming\swzy_bot\users\commands.py", line 12, in func_start
    markup = ReplyKeyboardMarkup()
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
2023-12-10 20:48:21,117 INFO Update id=683638707 is not handled. Duration 0 ms by bot id=6768503726
2023-12-10 20:48:21,117 ERROR Cause exception while process update id=683638707 by bot id=6768503726
ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
Traceback (most recent call last):
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\programming\swzy_bot\users\commands.py", line 12, in func_start
    markup = ReplyKeyboardMarkup()
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
2023-12-10 20:48:21,423 INFO Update id=683638708 is not handled. Duration 0 ms by bot id=6768503726
2023-12-10 20:48:21,423 ERROR Cause exception while process update id=683638708 by bot id=6768503726
ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
Traceback (most recent call last):
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\programming\swzy_bot\users\commands.py", line 12, in func_start
    markup = ReplyKeyboardMarkup()
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
2023-12-10 20:51:01,532 INFO Polling stopped
2023-12-10 20:51:02,173 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 20:51:32,501 INFO Start polling
2023-12-10 20:51:32,580 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 20:51:44,777 INFO Update id=683638709 is not handled. Duration 15 ms by bot id=6768503726
2023-12-10 20:51:44,778 ERROR Cause exception while process update id=683638709 by bot id=6768503726
ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
Traceback (most recent call last):
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\programming\swzy_bot\users\commands.py", line 12, in func_start
    markup = ReplyKeyboardMarkup()
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
2023-12-10 20:53:52,681 INFO Polling stopped
2023-12-10 20:53:53,352 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 20:54:14,848 INFO Start polling
2023-12-10 20:54:14,933 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 20:54:18,721 INFO Update id=683638710 is not handled. Duration 297 ms by bot id=6768503726
2023-12-10 20:54:18,721 ERROR Cause exception while process update id=683638710 by bot id=6768503726
ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
Traceback (most recent call last):
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\programming\swzy_bot\users\commands.py", line 13, in func_start
    markup = ReplyKeyboardMarkup()
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
2023-12-10 20:54:31,614 INFO Polling stopped
2023-12-10 20:54:32,017 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 20:54:44,306 INFO Start polling
2023-12-10 20:54:44,398 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 20:54:50,300 INFO Update id=683638711 is not handled. Duration 327 ms by bot id=6768503726
2023-12-10 20:54:50,301 ERROR Cause exception while process update id=683638711 by bot id=6768503726
ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
Traceback (most recent call last):
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\programming\swzy_bot\users\commands.py", line 13, in func_start
    markup = ReplyKeyboardMarkup()
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ReplyKeyboardMarkup
keyboard
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
2023-12-10 21:01:28,216 INFO Polling stopped
2023-12-10 21:01:28,825 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 21:01:32,091 INFO Start polling
2023-12-10 21:01:32,174 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 21:02:18,693 INFO Update id=683638712 is handled. Duration 671 ms by bot id=6768503726
2023-12-10 21:03:04,123 INFO Polling stopped
2023-12-10 21:03:04,799 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 21:03:14,886 INFO Start polling
2023-12-10 21:03:14,976 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 21:03:18,480 INFO Update id=683638713 is handled. Duration 406 ms by bot id=6768503726
2023-12-10 21:09:07,934 INFO Polling stopped
2023-12-10 21:09:08,503 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 21:44:18,686 INFO Start polling
2023-12-10 21:44:18,771 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 21:44:26,475 INFO Update id=683638714 is handled. Duration 422 ms by bot id=6768503726
2023-12-10 21:45:30,881 INFO Polling stopped
2023-12-10 21:45:31,440 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 21:45:35,004 INFO Start polling
2023-12-10 21:45:35,105 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 21:45:39,970 INFO Update id=683638715 is handled. Duration 468 ms by bot id=6768503726
2023-12-10 21:46:09,606 INFO Update id=683638716 is handled. Duration 422 ms by bot id=6768503726
2023-12-10 21:56:14,062 INFO Polling stopped
2023-12-10 21:56:14,622 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 21:57:23,798 INFO Start polling
2023-12-10 21:57:23,897 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 21:57:30,009 INFO Update id=683638717 is handled. Duration 389 ms by bot id=6768503726
2023-12-10 21:58:58,396 INFO Polling stopped
2023-12-10 21:58:59,969 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 21:59:51,755 INFO Start polling
2023-12-10 21:59:51,841 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 21:59:52,393 INFO Update id=683638718 is handled. Duration 422 ms by bot id=6768503726
2023-12-10 21:59:55,096 INFO Update id=683638719 is handled. Duration 264 ms by bot id=6768503726
2023-12-10 22:11:38,933 INFO Polling stopped
2023-12-10 22:11:39,513 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 22:26:20,533 INFO Start polling
2023-12-10 22:26:20,631 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 22:26:23,896 INFO Polling stopped
2023-12-10 22:26:24,692 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 22:26:54,755 INFO Start polling
2023-12-10 22:26:54,830 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 22:26:57,047 INFO Update id=683638720 is handled. Duration 311 ms by bot id=6768503726
2023-12-10 22:53:26,466 INFO Polling stopped
2023-12-10 22:53:27,027 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 22:53:40,985 INFO Start polling
2023-12-10 22:53:41,057 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 22:53:59,083 INFO Update id=683638721 is not handled. Duration 0 ms by bot id=6768503726
2023-12-10 22:53:59,083 ERROR Cause exception while process update id=683638721 by bot id=6768503726
TypeError: BaseModel.__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\programming\swzy_bot\users\commands.py", line 13, in func_start
    open_swzy = InlineKeyboardButton('Первая кнопка!', callback_data='button1')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseModel.__init__() takes 1 positional argument but 2 were given
2023-12-10 22:54:01,759 INFO Update id=683638722 is not handled. Duration 0 ms by bot id=6768503726
2023-12-10 22:54:01,759 ERROR Cause exception while process update id=683638722 by bot id=6768503726
TypeError: BaseModel.__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\programming\swzy_bot\users\commands.py", line 13, in func_start
    open_swzy = InlineKeyboardButton('Первая кнопка!', callback_data='button1')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseModel.__init__() takes 1 positional argument but 2 were given
2023-12-10 22:54:02,362 INFO Update id=683638723 is not handled. Duration 0 ms by bot id=6768503726
2023-12-10 22:54:02,362 ERROR Cause exception while process update id=683638723 by bot id=6768503726
TypeError: BaseModel.__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\programming\swzy_bot\users\commands.py", line 13, in func_start
    open_swzy = InlineKeyboardButton('Первая кнопка!', callback_data='button1')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseModel.__init__() takes 1 positional argument but 2 were given
2023-12-10 22:57:30,300 INFO Polling stopped
2023-12-10 22:57:30,864 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 22:57:52,879 INFO Start polling
2023-12-10 22:57:52,951 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 22:57:59,074 INFO Update id=683638724 is handled. Duration 407 ms by bot id=6768503726
2023-12-10 22:59:24,314 INFO Polling stopped
2023-12-10 22:59:24,931 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 22:59:29,335 INFO Start polling
2023-12-10 22:59:29,410 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 22:59:36,855 INFO Update id=683638725 is not handled. Duration 389 ms by bot id=6768503726
2023-12-10 22:59:36,855 ERROR Cause exception while process update id=683638725 by bot id=6768503726
TelegramBadRequest: Telegram server says - Bad Request: inline keyboard button Web App URL 'iridescent-duckanoo-20b130.netlify.app' is invalid: Only HTTPS links are allowed
Traceback (most recent call last):
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\programming\swzy_bot\users\commands.py", line 20, in func_start
    await message.answer(f"welcome to SWZY! co ltd", reply_markup=builder.as_markup())
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\client\bot.py", line 432, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 179, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: inline keyboard button Web App URL 'iridescent-duckanoo-20b130.netlify.app' is invalid: Only HTTPS links are allowed
2023-12-10 22:59:40,324 INFO Update id=683638726 is not handled. Duration 250 ms by bot id=6768503726
2023-12-10 22:59:40,324 ERROR Cause exception while process update id=683638726 by bot id=6768503726
TelegramBadRequest: Telegram server says - Bad Request: inline keyboard button Web App URL 'iridescent-duckanoo-20b130.netlify.app' is invalid: Only HTTPS links are allowed
Traceback (most recent call last):
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\programming\swzy_bot\users\commands.py", line 20, in func_start
    await message.answer(f"welcome to SWZY! co ltd", reply_markup=builder.as_markup())
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\client\bot.py", line 432, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 179, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\swzy_bot\venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: inline keyboard button Web App URL 'iridescent-duckanoo-20b130.netlify.app' is invalid: Only HTTPS links are allowed
2023-12-10 23:01:17,010 INFO Polling stopped
2023-12-10 23:01:17,622 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 23:01:20,868 INFO Start polling
2023-12-10 23:01:20,950 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-10 23:01:25,462 INFO Update id=683638727 is handled. Duration 453 ms by bot id=6768503726
2023-12-10 23:36:06,699 INFO Update id=683638728 is handled. Duration 516 ms by bot id=6768503726
2023-12-10 23:39:55,700 INFO Update id=683638729 is handled. Duration 437 ms by bot id=6768503726
2023-12-11 01:15:00,467 INFO Polling stopped
2023-12-11 01:15:01,006 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-11 01:15:05,975 INFO Start polling
2023-12-11 01:15:06,047 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-11 01:15:14,958 INFO Update id=683638730 is handled. Duration 375 ms by bot id=6768503726
2023-12-12 23:59:20,497 INFO Start polling
2023-12-12 23:59:20,578 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-12 23:59:20,915 INFO Polling stopped
2023-12-12 23:59:21,508 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-13 00:00:25,483 INFO Start polling
2023-12-13 00:00:25,576 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-13 00:00:33,621 INFO Update id=683638732 is handled. Duration 437 ms by bot id=6768503726
2023-12-13 00:06:17,970 INFO Polling stopped
2023-12-13 00:06:18,343 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-13 14:42:32,535 INFO Start polling
2023-12-13 14:42:32,607 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-13 14:42:37,799 INFO Update id=683638733 is handled. Duration 531 ms by bot id=6768503726
2023-12-13 14:43:20,718 INFO Update id=683638734 is handled. Duration 469 ms by bot id=6768503726
2023-12-13 14:45:07,136 INFO Update id=683638735 is handled. Duration 483 ms by bot id=6768503726
2023-12-13 14:46:38,166 INFO Update id=683638736 is handled. Duration 389 ms by bot id=6768503726
2023-12-13 18:00:14,158 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-13 18:00:14,158 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6768503726)
2023-12-13 18:00:25,398 INFO Connection established (tryings = 1, bot id = 6768503726)
2023-12-13 19:51:55,152 INFO Start polling
2023-12-13 19:51:55,232 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-13 19:51:58,298 INFO Update id=683638737 is handled. Duration 593 ms by bot id=6768503726
2023-12-13 19:52:06,846 INFO Update id=683638738 is handled. Duration 531 ms by bot id=6768503726
2023-12-13 19:52:29,442 INFO Update id=683638739 is handled. Duration 468 ms by bot id=6768503726
2023-12-13 19:52:56,455 INFO Update id=683638740 is handled. Duration 468 ms by bot id=6768503726
2023-12-13 19:53:58,828 INFO Update id=683638741 is handled. Duration 453 ms by bot id=6768503726
2023-12-13 20:19:38,447 INFO Update id=683638742 is handled. Duration 514 ms by bot id=6768503726
2023-12-13 20:25:43,747 INFO Update id=683638743 is handled. Duration 577 ms by bot id=6768503726
2023-12-13 20:36:13,615 INFO Update id=683638744 is handled. Duration 467 ms by bot id=6768503726
2023-12-13 20:39:02,775 INFO Update id=683638745 is not handled. Duration 0 ms by bot id=6768503726
2023-12-14 23:34:58,924 INFO Start polling
2023-12-14 23:34:59,000 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-14 23:35:25,072 INFO Start polling
2023-12-14 23:35:25,165 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-14 23:36:12,919 INFO Update id=683638746 is handled. Duration 421 ms by bot id=6768503726
2023-12-15 21:55:28,133 INFO Start polling
2023-12-15 21:55:28,224 INFO Run polling for bot @swzy_bot id=6768503726 - 'SWZY!'
2023-12-15 21:55:28,961 INFO Update id=683638750 is handled. Duration 531 ms by bot id=6768503726
2023-12-15 21:55:28,974 INFO Update id=683638754 is handled. Duration 547 ms by bot id=6768503726
2023-12-15 21:55:28,984 INFO Update id=683638747 is handled. Duration 547 ms by bot id=6768503726
2023-12-15 21:55:28,989 INFO Update id=683638753 is handled. Duration 547 ms by bot id=6768503726
2023-12-15 21:55:28,991 INFO Update id=683638751 is handled. Duration 562 ms by bot id=6768503726
2023-12-15 21:55:29,005 INFO Update id=683638748 is handled. Duration 578 ms by bot id=6768503726
2023-12-15 21:55:29,007 INFO Update id=683638752 is handled. Duration 578 ms by bot id=6768503726
2023-12-15 21:55:29,064 INFO Update id=683638749 is handled. Duration 625 ms by bot id=6768503726
2023-12-15 21:55:38,679 INFO Update id=683638755 is handled. Duration 265 ms by bot id=6768503726
2023-12-15 21:55:39,851 INFO Update id=683638756 is handled. Duration 375 ms by bot id=6768503726
2023-12-15 22:15:38,482 INFO Update id=683638757 is handled. Duration 562 ms by bot id=6768503726
2023-12-15 22:23:12,875 INFO Polling stopped
2023-12-15 22:23:13,441 INFO Polling stopped for bot @swzy_bot id=6768503726 - 'SWZY!'
